# Getting Started

## Overview

This page explains how to obtain the VisionEval software and install it, and
provides a brief overview of what to do with it after it is installed. Please
look at the Concept Primary to learn how VisionEval can support scenario
planning and help develop strategies to manage transportation system
performance.

The [Concept Primer](#concept-primer) and the [VisionEval Tutorial](#tutorial)
found later in this book contain more complete details on setting up VisionEval
models with local data, running scenarios, and extracting and analyzing results.

-   [Installation and Setup](#installation-and-setup)

-   [Workflow](#workflow-of-visioneval)

-   [Editing and Running Models](#editing-and-running-models)

-   [Getting Results](#running-and-extracting-results)

-   [Using the Walkthrough](#using-the-walkthrough)

VisionEval runs within the R Statistical Environment on any system for which R
is available. There are two paths to installing VisionEval:

1.  **Use the installation script**:

    This is the simplest way to quickly get VisionEval on your computer.

    1.  Install a recent version of R (see [pre-requisites](#pre-requisites) below),
        then start R, change the R working directory to a new empty folder, and
        copy this line into the R console:
        ```
        source(ve.url<-"https://visioneval.github.io/assets/install/VE4-install.R")
        ```
        If you just click through the defaults in the dialogs that appear, you'll
        get a running version of the latest release of VisionEval. Details later on
        this page explain how to customize your installation to support developing and
        running your own model version.

2.  **Copy or clone the Github code repository**:

    1.  You can copy a snapshot of the VisionEval code repository using the installation
        script.
    2.  Alternatively, you can clone the VisionEval Github repository (you don't need to
        "fork" the repository unless you're planning to contribute changes to main
        VisionEval code using Github's "pull request" mechanism).
    2.  The Github repository is [`VisionEval-4`](https://github.com/VisionEval/VisionEval-4).Once you
        have downloaded or cloned the VisionEval repository, you will
        need to build the VisionEval R packages before you can run models.
        Full instructions are provided below.

Detailed step-by-step setup instructions on setting up the VisionEval runtime, or building VisionEval from the source
code, can be found in on the [Detailed Installation Instructions](#detailed-installation) page.

## Installation and Setup

#### Pre-requisites

You will need:

-   [R, at least version 4.4.3](https://cran.r-project.org)

-   Optionally: [RStudio](https://www.rstudio.com/products/rstudio/download/)

Once you have R installed, you can run the VisionEval installer (RStudio is optional but many people find it useful for
managing the R environment).

VisionEval currently only has build support for Microsoft Windows. In principle, it will run on any operating system for
which R is available (meaning for Apple Macintosh or the main Linux distributions). However, building VisionEval for
those systems will require installing a series of operating system support packages that are typically not available by
default. An open development issue is to add automatic support for installing those packages; this documentation will
be updated once that work is complete.

#### Installer

Currently, VisionEval will run on any R version in the 4.4.x or 4.5.x series.

You can retrieve the current binary release of VisionEval by running the installation script as described here
(and [available on the website](https://visioneval.github.io/category/download.html)).

Start your selected version of R (using the built-in RGui or RStudio, either will work), 
then copy the following line into your R console:

```R
source(ve.url<-"https://visioneval.github.io/assets/install/VE4-install.R")
```

When the script starts, the first thing you should do is to "Change VE_HOME" to a suitable location.
VE_HOME is where your VisionEval will be installed and it should be an empty folder. If you don't
have one ready, you can create one when you push the "Change VE_HOME" button. Beware that the default
suggested if you are starting fresh is usually NOT appropriate.

See below for further details (or you can select the defaults on the remaining installation screens).

**GORY DETAIL** The most up-to-date installer scripts can be found within the Github source tree in
[`sources/framework/VEStart/inst/download`](https://github.com/VisionEval/VisionEval-4/tree/release/sources/framework/VEStart/inst/download)
, or within the `download` folder of the installed VEStart package, which you can locate with the R command
`system.file("download",package="VEStart")`

**ADDITIONAL GORY DETAIL** The mysterious `ve.url<-` incantation enables some tcltk dialogs (in file
`VE4-UI-tcltk.R`) stored in a separate script file that give you flexibility in using releases other
than the most current, or in downloading a snapshot of the full VisionEval code without using Git so
you can build the entire system locally. If you leave it out, you'll get a forced installation in your current
R working folder with the latest binary release.

When the installation is complete, VisionEval will automatically start with your selected runtime
directory as the R working directory. And you will see a startup message indicating that you are
running VisionEval (your version of R may differ):

```
R version 4.5.2 (2025-10-31 ucrt) -- "[Not] Part in a Rumble"
Copyright (C) 2025 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

If VisionEval does not start automatically, please run this command:
startVisionEval()
Setting up VE_RUNTIME as N:/VisionEval
Adding startup files to N:/VisionEval
Welcome to VisionEval 4.0!
Running in N:/VisionEval
> 
```

From there, you can explore the
[tutorial instructions](https://visioneval.github.io/docs/getting-started.html#workflow-of-visioneval)
later in this documentation.

#### Starting VisionEval once it is installed

Once you have installed VisionEval, to start it again follow these steps:

1. Navigate to the folder in which you installed VisionEval (technically, VE_HOME or VE_RUNTIME, explained below).

2. Double-click `VisionEval.Rproj`, if you have RStudio installed. This will start whatever R version
   you have told RStudio to use (defaulting to the most recently installed version of R). That has to be
   the same as the R version you used to run the installation script.

3. Double click `launch_R4.5.2.bat`, if you don't have RStudio or just want to use the standard R GUI.
   (The numbers in the `launch_Rx.y.z.bat` file name will match the version of R with which you
   installed VisionEval). There may be several `launch` files if you have installed VisionEval for
   different R versions in the same VE_HOME directory (something that will work, though it is not
   recommended to avoid confusion).   

#### Starting VisionEval from within R

If you need to start VisionEval from within R for some reason (e.g. you started R or RStudio from the Windows
Start Menu and it is not set to use your VisionEval folder), just change into your VisionEval folder using

-   RStudio's `Session / Set Working Directory...` menu option, or

-   In plain R, the `File / Change dir...` menu option, or the `setwd` command
    on the R command line.

Then run this instruction to start VisionEval:

```
source(".Rprofile")
```

You should then be running VisionEval (Look for the message `Loading VisionEval 4.0!`.

If that doesn't work, check that your R working directory is correct, and that VisionEval has actually been installed in
that directory. If you still have trouble, try re-installing VisionEval using the instructions above.

## Workflow of VisionEval

VisionEval models and the underlying software framework are written in the
[R programming language](https://www.r-project.org) for statistical computing and graphics.
The purpose of the model system and framework is to enable models be created in a plug-and-play fashion from VisionEval
modules that are distributed as R packages. A simple R script is used to implement a model by initializing the model
environment and then calling modules successively. Scenarios are then constructed through a set of files that provide
variant model inputs for evaluation and comparison.

To use VisionEval to evaluate scenarios, there are several elements that users
need to set up:

1.  Select and install one of the [VisionEval
    models](https://github.com/VisionEval/VisionEval/wiki/VisionEval-Models),
    customizing it as needed:

    1.  [VERSPM](https://github.com/VisionEval/VisionEval-Dev/blob/readme-dev/docs/tutorials/verspm/Main.md)
        – Regional Strategic Planning Model

    2.  [VE-State](https://github.com/VisionEval/VisionEval/wiki/VE-State-Status)
        – VisionEval State-Level Model

    2.  **Currently not Supported** [VERPAT](https://github.com/VisionEval/VisionEval/wiki/VERPAT-Tutorial-Overview)
        – Rapid Policy Analysis Tool

2.  Develop a *Base Model* for the region under analysis. The Base Model
    specifies:

    1.  **Model Geography** (zone structure), reported as Marea (metropolitan
        area), AZones (county-sized), and BZones (often census-tract-sized or
        could be related to Traffic Analysis Zones in other travel demand
        models) and related configuration files

    2.  **Base and Future Years** to be evaluated for each scenario (e.g., 2019
        and 2050)

    3.  **Local Data Files** describing Base Scenario conditions in the region
        (including both observed base year data, and estimates of future year
        conditions with no scenario policies applied)

3.  Develop variant *Future Actions* and *Scenarios*, by adjusting specific
    input elements for the Future Years. VisionEval models support having many
    different scenarios. See the scenario development chapter later in this book
    for details.

4.  Run the model to process each of its scenarios.

5.  Extract or query the results for summarization and further analysis in R or
    export tabular data files to other data analysis systems (including spreadsheets
    or SQL databases).

These steps are described in detail on other pages of this documentation.

## Editing and Running Models

As described in the [model tutorials](#visioneval-tutorials), a VisionEval Model
contains the following components:

-   Model configuration: `visioneval.cnf`

-   The model script file, typically called `run_model.R` (sometimes in a
    `/scripts` sub-folder), which describes the steps that will be performed
    when the model runs

-   Global parameters describing the model geography, preferred data units, and
    currency conversion deflators in the `/defs` sub-folder

-   Base Model Input data in the `/inputs` sub-folder

-   Pre-defined query scripts (in the `/queries` sub-folder) that can extract
    useful metrics from the model scenarios once they have run

-   Additional optional folders for the model scenarios (either as top-level
    directories or within the `/scenarios` sub-folder), which describe
    deviations from the Base Model. Scenarios may have different
    inputs or a different model script.

Once any of the model scenarios have been run, the model will also have a
`/results` sub-folder. After queries have been run or raw results extracted into
a tabular data format like `.csv`, there will be a sub-folder within `/results`
called `/output`.

See the tutorial chapters later in this book for instructions on how to set up
VisionEval for your study area. Typically, you will start by installing one of
the standard models and then adjusting `visioneval.cnf`, `/defs` and `/inputs`
to complete your Base Model. Once you have completed the Base Model, you
can add scenarios to your model (as described later) by varying a few inputs to
describe alternate future conditions.

## Running VisionEval Models

VisionEval includes a simple R command-line interface for running models and
extracting their results.

The tutorials later in this book will explain how to select and customize one of
the VisionEval models, as well as how to develop inputs and create scenarios for
your area.

Once VisionEval is running in an R or Rstudio console, you can try things out by copying or entering
the following instructions into the R Console window:

```
rspm <- installModel("VERSPM")
rspm$run()
results <- rspm$results()
results$export()
query <- rspm$query("Full-Query")
query$run()
query$export()
```

The instructions will do the following:

-   Install the sample VisionEval RSPM (Regional Strategic Planning Model)

    -   The model has data from the small Rogue Valley MPO in Oregon

    -   The model is installed in `VisionEval/models/VERSPM-base`

    -   You can re-open the model later by using this instruction;

        ```
        rspm <- openModel("VERSPM-base")
        ```

-   Run the model

    -   The results are placed in `VisionEval/models/VERSPM-base/results`

    -   The results are in a difficult internal R format, so you’ll want to
        export them into something more useful for subsequent analysis.

-   Export the model results into several files in a friendly text table format
    (.csv) that you can open with Excel or a text editor

    -   The CSV files are placed in a dated subfolder of
        `VisionEval/models/VERSPM-base/results/outputs`

    -   You can export the results into an SQLite database (created in the
        `outputs` folder) by using this export instruction:

        ```
        rspm$export("sql")
        ```

-   Run a set of basic queries to report summary model performance metrics

    -   When exported, those metrics appear in .csv files in another subfolder of
        `VisionEval/models/VERSPM-base/results/outputs`
    -   By default, the query output file has one row per metric and one column per
        model scenario.

## Using the Walkthrough

Additional features of the VisionEval R interface are somewhat systematically explored in commented R scripts located in
the VisionEval runtime `VisionEval/walkthrough` folder. The walkthrough files are most easily explored using RStudio.

Once VisionEval is running, you can set up the walkthrough by running this instruction:

```
ve.walkthrough()
```

The walkthrough will create a special runtime directory (within your main
runtime folder), so nothing you do while trying it out will affect any of your
"real" models, which will remain untouched in your "models" directory.

It will also print the path of a folder that you can use in RStudio (or copy into
Windows Explorer) to see the walkthrough script files.

To explore any of the walkthrough scripts:

-   Open the script in the RStudio script editor by navigating in the RStudio
    "Files" pane to the VisionEval/walkthrough directory, then double-clicking
    one of the scripts.

-   Select individual lines in script editor and press "Enter" to run that line
    in the console. You should run the lines in order ("walk through them") and
    not skip any! The commented lines (starting with “\#” describe what is going
    on).

If things get messed up because you didn't run the walkthrough lines in order,
it's usually enough to back up and run the lines you skipped. If you need to,
you can reset the walkthrough by starting it like this:

```
walkthrough(reset=TRUE)
```

Be careful: the "reset=TRUE" instruction will clear the walkthrough runtime.
Anything you saved there (including outputs from running and exporting the test
models) will be lost. Your regular runtime models directory will remain
untouched.

Here is an overview of the walkthrough files and what you will learn from each
of them:

-   `00-walkthrough.R` : Master list of walkthrough scripts (nothing specific to
    run here - it's just a script listing the other scripts)

-   `01-install.R` : How to install various VisionEval model sample from the packaged
    examples

-   `02-running.R` : Running (or re-running) a VisionEval model

-   `03-extract.R` : Getting raw results (or a subset) from a VisionEval model

-   `03A-advanced-export.R` : Exporting to other file formats (SQL or Excel)

-   `04-scenarios.R` : Working with model scenarios - this is about running them,
    not setting them up

-   `05-queries.R` : How to run queries to generate summary metrics of model results
    (including sets of scenarios)
